# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build and VM configuration
build:
  os: 'ubuntu-22.04'
  tools:
    python: '3.10'

# Python requirements
python:
  install:
    - requirements: requirements-rtd.txt
    - method: pip
      path: .

# Build with sphinx
sphinx:
  configuration: doc/source/conf.py

# Build all the things
formats: all
