"""
Defines JSON schemas to validate dictionaries generated by Inventory objects.

Name:        schema.py
Exposes:
             schema_flat (dict)    -- Defines JSON structure for flat_dict
                                      Inventory export
             subschema_flat (dict) -- JSON structure for individual data
                                      objects, within `schema_flat`

             schema_struct (dict)      -- Defines JSON structure for dicts
                                          composited with DataObjStr method
                                          update_struct_dict. Composed using
                                          subschema_struct_xxx
             subschema_struct_branch_2 (dict) -- [COMPLETE THIS]
             subschema_struct_branch_1 (dict) -- [COMPLETE THIS]
             subschema_struct_leaf (dict) -- [COMPLETE THIS]

Author:      Brian Skinn (bskinn@alum.mit.edu)

Created:     7 Dec 2017
Copyright:   (c) Brian Skinn 2016-2018
License:     The MIT License; see "LICENSE.txt" for full license terms
             and contributor agreement.

This file is part of Sphinx Objects.inv Encoder/Decoder, a toolkit for
encoding and decoding objects.inv files for use with intersphinx.

http://www.github.com/bskinn/sphobjinv

"""


# For jsonschema Draft 4.
# Schemas are defined with static field names as a versioning
# guarantee, instead of basing them dynamically on DataFields, etc.

# Flat dict schema
subschema_flat = {'name': {'type': 'string'},
                  'domain': {'type': 'string'},
                  'role': {'type': 'string'},
                  'priority': {'type': 'string'},
                  'uri': {'type': 'string'},
                  'dispname': {'type': 'string'}
                  }

schema_flat = {'$schema': "http://json-schema.org/schema#",
               'type': 'object',
               'properties': {'project': {'type': 'string'},
                              'version': {'type': 'string'},
                              'count': {'type': 'integer'},
                              'metadata': {'type': 'object'}
                              },
               'patternProperties': {'^\\d+': {'type': 'object',
                                               'properties': subschema_flat,
                                               'additionalProperties': False,
                                               'required': list(subschema_flat)
                                               }
                                     },
               'additionalProperties': False,
               'required': ['project', 'version', 'count']
               }
