name: 'ALL: Run tests on Python 3.12'

on:
  - pull_request

jobs:
  current_python_tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        python-version:
          - '3.12'
    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "${{ matrix.python-version }}"
        cache: 'pip'
        cache-dependency-path: requirements-ci.txt

    - name: Update pip
      run: python -m pip install -U pip

    - name: Install & report CI dependencies
      run: |
        python -m pip install -U --force-reinstall -r requirements-ci.txt
        python --version
        pip list

    - name: Build docs
      run: |
        cd doc
        make html
        mkdir scratch

    - name: Run tests & report source coverage
      run: |
        pytest --cov --testall --nonloc
        coverage xml -o coverage-service.xml

    - name: Submit to Codecov if Linux, ready status, and main/stable
      if: ${{ matrix.os == 'ubuntu-latest' && !github.event.pull_request.draft && (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'stable') }}
      uses: codecov/codecov-action@v5.3.1
      with:
        name: 'service'-${{ github.run_id }}
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: bskinn/sphobjinv
        os: linux
        flags: unittests
        files: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        verbose: true
