name: Constants Definition

on:
  workflow_call:

jobs:
  define_constants:
    name: Define constants
    runs-on: ubuntu-latest
    outputs:
      CURRENT_PYTHON: '3.12'

    steps:
      - name: Trivial step
        run: |
          echo "There needs to be *something* for the job to do..."
