name: Constants Definition

on:
  workflow_call:

jobs:
  define_constants:
    name: Define constants
    runs-on: ubuntu-latest
    outputs:
      CURRENT_PYTHON: ${{ steps.define.outputs.current_python }}

    steps:
      - name: Define constants
        id: define
        run: |
          echo "current_python=3.12" >> "$GITHUB_OUTPUT"

  report_constants:
    name: Report constants definition
    runs-on: ubuntu-latest
    needs: define_constants
    steps:
      - name: Report the constants
        run: |
          echo "${{ toJson(needs.define_constants.outputs) }}"
      - name: Report the specific constant
        run: echo "${{ needs.define_constants.outputs.CURRENT_PYTHON }}"
