name: 'RELEASE: Check flake8 noqas'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - stable

jobs:
  check_flake8_noqa:
    name: are all relevant (nofail)
    runs-on: 'ubuntu-latest'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: requirements-ci.txt

    - name: Install tox
      run: pip install tox

    - name: Run never-fail flake8-with-noqa
      run: tox -e flake8_noqa
